%%% @doc Syscall definitions for the matrix test infrastructure.
%%%
%%% Complete registry of x86_64 syscalls with tier classification
%%% for test generation.
%%%
%%% Tiers:
%%%   normal    - zeroed args return error (EFAULT/EBADF/EINVAL), safe
%%%   timed     - needs special args to avoid blocking (timeout=0)
%%%   exit_like - the syscall IS the exit, no trailing exit needed
%%%   blocking  - would hang with any args, skip
%%%   skip      - reserved/unimplemented/dangerous, skip
-module(syscall_defs).

-export([x86_64/0]).

%% @doc Returns [{Nr, Name, Tier, AsmArgs}] for all x86_64 syscalls.
%% AsmArgs is a list of {Reg, Value} pairs for non-default register setup.
%% Default: all arg registers zeroed (xor edi,edi; xor esi,esi; xor edx,edx).
-spec x86_64() -> [{non_neg_integer(), atom(), atom(), list()}].
x86_64() ->
    [
        {0,   read,                   normal, []},
        {1,   write,                  normal, []},
        {2,   open,                   normal, []},
        {3,   close,                  normal, []},
        {4,   stat,                   normal, []},
        {5,   fstat,                  normal, []},
        {6,   lstat,                  normal, []},
        {7,   poll,                   normal, [{rdx, 0}]},  % timeout_ms=0
        {8,   lseek,                  normal, []},
        {9,   mmap,                   normal, []},
        {10,  mprotect,              normal, []},
        {11,  munmap,                normal, []},
        {12,  brk,                   normal, []},
        {13,  rt_sigaction,          normal, []},
        {14,  rt_sigprocmask,        normal, []},
        {15,  rt_sigreturn,          skip, []},  % must be called from signal context
        {16,  ioctl,                 normal, []},
        {17,  pread64,              normal, []},
        {18,  pwrite64,             normal, []},
        {19,  readv,                 normal, []},
        {20,  writev,                normal, []},
        {21,  access,                normal, []},
        {22,  pipe,                  normal, []},
        {23,  select,                timed,  [{rdi, 0}, {r8, stack_zero_timeval}]},
        {24,  sched_yield,           normal, []},
        {25,  mremap,                normal, []},
        {26,  msync,                 normal, []},
        {27,  mincore,               normal, []},
        {28,  madvise,               normal, []},
        {29,  shmget,                normal, []},
        {30,  shmat,                 normal, []},
        {31,  shmctl,                normal, []},
        {32,  dup,                   normal, []},
        {33,  dup2,                  normal, []},
        {34,  pause,                 blocking, []},
        {35,  nanosleep,             normal, []},  % NULL rdi → EFAULT
        {36,  getitimer,             normal, []},
        {37,  alarm,                 normal, []},
        {38,  setitimer,             normal, []},
        {39,  getpid,                normal, []},
        {40,  sendfile,              normal, []},
        {41,  socket,                normal, []},
        {42,  connect,               normal, []},
        {43,  accept,                normal, []},
        {44,  sendto,                normal, []},
        {45,  recvfrom,              normal, []},
        {46,  sendmsg,               normal, []},
        {47,  recvmsg,               normal, []},
        {48,  shutdown,              normal, []},
        {49,  bind,                  normal, []},
        {50,  listen,                normal, []},
        {51,  getsockname,           normal, []},
        {52,  getpeername,           normal, []},
        {53,  socketpair,            normal, []},
        {54,  setsockopt,            normal, []},
        {55,  getsockopt,            normal, []},
        {56,  clone,                 normal, []},
        {57,  fork,                  normal, []},
        {58,  vfork,                 skip, []},  % actually forks, complicates test
        {59,  execve,                normal, []},  % NULL argv → EFAULT
        {60,  exit,                  exit_like, []},
        {61,  wait4,                 normal, []},
        {62,  kill,                  normal, []},
        {63,  uname,                 normal, []},
        {64,  semget,                normal, []},
        {65,  semop,                 normal, []},
        {66,  semctl,                normal, []},
        {67,  shmdt,                 normal, []},
        {68,  msgget,                normal, []},
        {69,  msgsnd,                normal, []},
        {70,  msgrcv,                normal, []},
        {71,  msgctl,                normal, []},
        {72,  fcntl,                 normal, []},
        {73,  flock,                 normal, []},
        {74,  fsync,                 normal, []},
        {75,  fdatasync,             normal, []},
        {76,  truncate,              normal, []},
        {77,  ftruncate,             normal, []},
        {78,  getdents,              normal, []},
        {79,  getcwd,                normal, []},
        {80,  chdir,                 normal, []},
        {81,  fchdir,                normal, []},
        {82,  rename,                normal, []},
        {83,  mkdir,                 normal, []},
        {84,  rmdir,                 normal, []},
        {85,  creat,                 normal, []},
        {86,  link,                  normal, []},
        {87,  unlink,                normal, []},
        {88,  symlink,               normal, []},
        {89,  readlink,              normal, []},
        {90,  chmod,                 normal, []},
        {91,  fchmod,                normal, []},
        {92,  chown,                 normal, []},
        {93,  fchown,                normal, []},
        {94,  lchown,                normal, []},
        {95,  umask,                 normal, []},
        {96,  gettimeofday,          normal, []},
        {97,  getrlimit,             normal, []},
        {98,  getrusage,             normal, []},
        {99,  sysinfo,               normal, []},
        {100, times,                 normal, []},
        {101, ptrace,                normal, []},
        {102, getuid,                normal, []},
        {103, syslog,                normal, []},
        {104, getgid,                normal, []},
        {105, setuid,                normal, []},
        {106, setgid,                normal, []},
        {107, geteuid,               normal, []},
        {108, getegid,               normal, []},
        {109, setpgid,               normal, []},
        {110, getppid,               normal, []},
        {111, getpgrp,               normal, []},
        {112, setsid,                normal, []},
        {113, setreuid,              normal, []},
        {114, setregid,              normal, []},
        {115, getgroups,             normal, []},
        {116, setgroups,             normal, []},
        {117, setresuid,             normal, []},
        {118, getresuid,             normal, []},
        {119, setresgid,             normal, []},
        {120, getresgid,             normal, []},
        {121, getpgid,               normal, []},
        {122, setfsuid,              normal, []},
        {123, setfsgid,              normal, []},
        {124, getsid,                normal, []},
        {125, capget,                normal, []},
        {126, capset,                normal, []},
        {127, rt_sigpending,         normal, []},
        {128, rt_sigtimedwait,       normal, []},  % NULL → EFAULT
        {129, rt_sigqueueinfo,       normal, []},
        {130, rt_sigsuspend,         blocking, []},
        {131, sigaltstack,           normal, []},
        {132, utime,                 normal, []},
        {133, mknod,                 normal, []},
        {134, uselib,                skip, []},     % unimplemented
        {135, personality,           normal, []},
        {136, ustat,                 normal, []},
        {137, statfs,                normal, []},
        {138, fstatfs,               normal, []},
        {139, sysfs,                 normal, []},
        {140, getpriority,           normal, []},
        {141, setpriority,           normal, []},
        {142, sched_setparam,        normal, []},
        {143, sched_getparam,        normal, []},
        {144, sched_setscheduler,    normal, []},
        {145, sched_getscheduler,    normal, []},
        {146, sched_get_priority_max, normal, []},
        {147, sched_get_priority_min, normal, []},
        {148, sched_rr_get_interval, normal, []},
        {149, mlock,                 normal, []},
        {150, munlock,               normal, []},
        {151, mlockall,              normal, []},
        {152, munlockall,            normal, []},
        {153, vhangup,               normal, []},
        {154, modify_ldt,            normal, []},
        {155, pivot_root,            normal, []},
        {156, '_sysctl',             normal, []},
        {157, prctl,                 normal, []},
        {158, arch_prctl,            normal, []},
        {159, adjtimex,              normal, []},
        {160, setrlimit,             normal, []},
        {161, chroot,                normal, []},
        {162, sync,                  normal, []},
        {163, acct,                  normal, []},
        {164, settimeofday,          normal, []},
        {165, mount,                 normal, []},
        {166, umount2,               normal, []},
        {167, swapon,                normal, []},
        {168, swapoff,               normal, []},
        {169, reboot,                normal, []},  % EPERM without root
        {170, sethostname,           normal, []},
        {171, setdomainname,         normal, []},
        {172, iopl,                  normal, []},
        {173, ioperm,                normal, []},
        {174, create_module,         skip, []},     % historic stub
        {175, init_module,           normal, []},
        {176, delete_module,         normal, []},
        {177, get_kernel_syms,       skip, []},     % historic stub
        {178, query_module,          skip, []},     % historic stub
        {179, quotactl,              normal, []},
        {180, nfsservctl,            skip, []},     % historic stub
        {181, getpmsg,               skip, []},     % historic stub
        {182, putpmsg,               skip, []},     % historic stub
        {183, afs_syscall,           skip, []},     % historic stub
        {184, tuxcall,               skip, []},     % historic stub
        {185, security,              skip, []},     % historic stub
        {186, gettid,                normal, []},
        {187, readahead,             normal, []},
        {188, setxattr,              normal, []},
        {189, lsetxattr,             normal, []},
        {190, fsetxattr,             normal, []},
        {191, getxattr,              normal, []},
        {192, lgetxattr,             normal, []},
        {193, fgetxattr,             normal, []},
        {194, listxattr,             normal, []},
        {195, llistxattr,            normal, []},
        {196, flistxattr,            normal, []},
        {197, removexattr,           normal, []},
        {198, lremovexattr,          normal, []},
        {199, fremovexattr,          normal, []},
        {200, tkill,                 normal, []},
        {201, time,                  normal, []},
        {202, futex,                 normal, []},  % NULL → EFAULT
        {203, sched_setaffinity,     normal, []},
        {204, sched_getaffinity,     normal, []},
        {205, set_thread_area,       normal, []},
        {206, io_setup,              normal, []},
        {207, io_destroy,            normal, []},
        {208, io_getevents,          normal, []},  % bad ctx → EINVAL
        {209, io_submit,             normal, []},
        {210, io_cancel,             normal, []},
        {211, get_thread_area,       normal, []},
        {212, lookup_dcookie,        normal, []},
        {213, epoll_create,          normal, []},
        {214, epoll_ctl_old,         skip, []},     % deprecated
        {215, epoll_wait_old,        skip, []},     % deprecated
        {216, remap_file_pages,      normal, []},
        {217, getdents64,            normal, []},
        {218, set_tid_address,       normal, []},
        {219, restart_syscall,       skip, []},     % only valid after interrupted syscall
        {220, semtimedop,            normal, []},  % bad semid → EINVAL
        {221, fadvise64,             normal, []},
        {222, timer_create,          normal, []},
        {223, timer_settime,         normal, []},
        {224, timer_gettime,         normal, []},
        {225, timer_getoverrun,      normal, []},
        {226, timer_delete,          normal, []},
        {227, clock_settime,         normal, []},
        {228, clock_gettime,         normal, []},
        {229, clock_getres,          normal, []},
        {230, clock_nanosleep,       normal, []},  % NULL → EFAULT/EINVAL
        {231, exit_group,            exit_like, []},
        {232, epoll_wait,            normal, []},  % bad fd → EBADF
        {233, epoll_ctl,             normal, []},
        {234, tgkill,                normal, []},
        {235, utimes,                normal, []},
        {236, vserver,               skip, []},     % historic stub
        {237, mbind,                 normal, []},
        {238, set_mempolicy,         normal, []},
        {239, get_mempolicy,         normal, []},
        {240, mq_open,               normal, []},
        {241, mq_unlink,             normal, []},
        {242, mq_timedsend,          normal, []},
        {243, mq_timedreceive,       normal, []},
        {244, mq_notify,             normal, []},
        {245, mq_getsetattr,         normal, []},
        {246, kexec_load,            normal, []},
        {247, waitid,                normal, []},
        {248, add_key,               normal, []},
        {249, request_key,           normal, []},
        {250, keyctl,                normal, []},
        {251, ioprio_set,            normal, []},
        {252, ioprio_get,            normal, []},
        {253, inotify_init,          normal, []},
        {254, inotify_add_watch,     normal, []},
        {255, inotify_rm_watch,      normal, []},
        {256, migrate_pages,         normal, []},
        {257, openat,                normal, []},
        {258, mkdirat,               normal, []},
        {259, mknodat,               normal, []},
        {260, fchownat,              normal, []},
        {261, futimesat,             normal, []},
        {262, newfstatat,            normal, []},
        {263, unlinkat,              normal, []},
        {264, renameat,              normal, []},
        {265, linkat,                normal, []},
        {266, symlinkat,             normal, []},
        {267, readlinkat,            normal, []},
        {268, fchmodat,              normal, []},
        {269, faccessat,             normal, []},
        {270, pselect6,              timed,  [{rdi, 0}, {r8, stack_zero_timespec}]},
        {271, ppoll,                 timed,  [{rsi, 0}, {rdx, stack_zero_timespec}]},
        {272, unshare,               normal, []},
        {273, set_robust_list,       normal, []},
        {274, get_robust_list,       normal, []},
        {275, splice,                normal, []},
        {276, tee,                   normal, []},
        {277, sync_file_range,       normal, []},
        {278, vmsplice,              normal, []},
        {279, move_pages,            normal, []},
        {280, utimensat,             normal, []},
        {281, epoll_pwait,           normal, []},
        {282, signalfd,              normal, []},
        {283, timerfd_create,        normal, []},
        {284, eventfd,               normal, []},
        {285, fallocate,             normal, []},
        {286, timerfd_settime,       normal, []},
        {287, timerfd_gettime,       normal, []},
        {288, accept4,               normal, []},
        {289, signalfd4,             normal, []},
        {290, eventfd2,              normal, []},
        {291, epoll_create1,         normal, []},
        {292, dup3,                  normal, []},
        {293, pipe2,                 normal, []},
        {294, inotify_init1,         normal, []},
        {295, preadv,                normal, []},
        {296, pwritev,               normal, []},
        {297, rt_tgsigqueueinfo,     normal, []},
        {298, perf_event_open,       normal, []},
        {299, recvmmsg,              normal, []},  % bad fd → EBADF
        {300, fanotify_init,         normal, []},
        {301, fanotify_mark,         normal, []},
        {302, prlimit64,             normal, []},
        {303, name_to_handle_at,     normal, []},
        {304, open_by_handle_at,     normal, []},
        {305, clock_adjtime,         normal, []},
        {306, syncfs,                normal, []},
        {307, sendmmsg,              normal, []},
        {308, setns,                 normal, []},
        {309, getcpu,                normal, []},
        {310, process_vm_readv,      normal, []},
        {311, process_vm_writev,     normal, []},
        {312, kcmp,                  normal, []},
        {313, finit_module,          normal, []},
        {314, sched_setattr,         normal, []},
        {315, sched_getattr,         normal, []},
        {316, renameat2,             normal, []},
        {317, seccomp,               normal, []},
        {318, getrandom,             normal, []},
        {319, memfd_create,          normal, []},
        {320, kexec_file_load,       normal, []},
        {321, bpf,                   normal, []},
        {322, execveat,              normal, []},
        {323, userfaultfd,           normal, []},
        {324, membarrier,            normal, []},
        {325, mlock2,                normal, []},
        {326, copy_file_range,       normal, []},
        {327, preadv2,               normal, []},
        {328, pwritev2,              normal, []},
        {329, pkey_mprotect,         normal, []},
        {330, pkey_alloc,            normal, []},
        {331, pkey_free,             normal, []},
        {332, statx,                 normal, []},
        {333, io_pgetevents,         normal, []},
        {334, rseq,                  normal, []},
        {335, uretprobe,             skip, []},     % kernel internal
        %% 336-423: reserved gap
        {424, pidfd_send_signal,     normal, []},
        {425, io_uring_setup,        normal, []},
        {426, io_uring_enter,        normal, []},
        {427, io_uring_register,     normal, []},
        {428, open_tree,             normal, []},
        {429, move_mount,            normal, []},
        {430, fsopen,                normal, []},
        {431, fsconfig,              normal, []},
        {432, fsmount,               normal, []},
        {433, fspick,                normal, []},
        {434, pidfd_open,            normal, []},
        {435, clone3,                normal, []},  % NULL → EFAULT
        {436, close_range,           normal, []},
        {437, openat2,               normal, []},
        {438, pidfd_getfd,           normal, []},
        {439, faccessat2,            normal, []},
        {440, process_madvise,       normal, []},
        {441, epoll_pwait2,          normal, []},
        {442, mount_setattr,         normal, []},
        {443, quotactl_fd,           normal, []},
        {444, landlock_create_ruleset, normal, []},
        {445, landlock_add_rule,     normal, []},
        {446, landlock_restrict_self, normal, []},
        {447, memfd_secret,          normal, []},
        {448, process_mrelease,      normal, []},
        {449, futex_waitv,           normal, []},
        {450, set_mempolicy_home_node, normal, []},
        {451, cachestat,             normal, []},
        {452, fchmodat2,             normal, []},
        {453, map_shadow_stack,      normal, []},
        {454, futex_wake,            normal, []},
        {455, futex_wait,            normal, []},
        {456, futex_requeue,         normal, []},
        {457, statmount,             normal, []},
        {458, listmount,             normal, []},
        {459, lsm_get_self_attr,     normal, []},
        {460, lsm_set_self_attr,     normal, []},
        {461, lsm_list_modules,      normal, []},
        {462, mseal,                 normal, []}
    ].
