%% Seccomp profile record
%% Generated by elf_seccomp from ELF syscall analysis.

-ifndef(ELF_SECCOMP_HRL).
-define(ELF_SECCOMP_HRL, true).

-record(seccomp_profile, {
    arch           :: x86_64 | aarch64,
    default_action :: kill_process | errno,
    syscalls       :: ordsets:ordset(non_neg_integer()),  %% allowed syscall numbers
    names          :: ordsets:ordset(binary()),            %% allowed syscall names
    unresolved     :: non_neg_integer()                    %% how many couldn't be resolved
}).

-endif.
