%%
%% Copyright 2026 Erlkoenig Contributors
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%     http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.
%%

%% Seccomp profile record
%% Generated by elf_seccomp from ELF syscall analysis.

-ifndef(ELF_SECCOMP_HRL).
-define(ELF_SECCOMP_HRL, true).

-record(seccomp_profile, {
    arch :: x86_64 | aarch64,
    default_action :: kill_process | errno,
    %% allowed syscall numbers
    syscalls :: ordsets:ordset(non_neg_integer()),
    %% allowed syscall names
    names :: ordsets:ordset(binary()),
    %% how many couldn't be resolved
    unresolved :: non_neg_integer()
}).

-endif.
